# Generated by Django 4.1.1 on 2022-10-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pay_method', models.CharField(max_length=25)),
                ('amount', models.FloatField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('order_date', models.DateField()),
            ],
        ),
    ]
