# Generated by Django 4.1.1 on 2022-10-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_invoices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
